### ISSUE TITLE
Nordic Workshop

### ISSUE THREAD

**Issue by Electro-Mike** [sigurdnev/nordic_workshop#1]
Would you have a downloadable file with the added stuff for the COMMAND_1 and PWM? I tried entering the info for the COMMAND_1 LED on and I was getting multiple errors! It maybe that I am putting things in the wrong order.
I hope you can help me!

Thank you!
Mike
sandman@arquillalabs.com

**Comment by sigurdnev** [comment]
Hi Mike,

You should take a look at the code in the "complete" branch. https://github.com/sigurdnev/nordic_workshop/blob/complete/ble_app_uart/main.c
